---
name: DCO Exception Request
description: Submit an exception request
title: "[DCO Exception Request] [Project]"
labels:
  - licensing
assignees: krook,jeefy,joannalee333
body:
  - type: markdown
    attributes:
      value: |
        # Read before proceeding

        Before submitting this DCO Exception Request, please familiarize yourself with the following:

        - the CNCF IP Policy, from [section 11 of the CNCF Charter](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy), particularly 11(b) and 11(c)
        - the [reasons why the DCO is used and how it can be installed easily as a GitHub app](https://github.com/apps/dco)

        <br />

        ---

        # DCO Exception Request form

        For any components where none of the above criteria are met, please complete the form below.


  - type: markdown
    attributes:
      value: |
        <br />
        
        ## :clipboard: Project details

        The following information will help facilitate the review by the CNCF Legal Committee and Governing Board, and will help minimize further questions during review.


  - type: input
    id: project_name
    attributes:
      label: "For which CNCF project are you requesting exceptions?"
    validations:
      required: true

  - type: dropdown
    id: is_maintainer
    attributes:
      label: "Are you an official maintainer of this project?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />
        
        ## :newspaper: Exception details
        
        Please fill in the table below, with one row for each unique component for which a license exception is requested. In the "Purpose" column, please briefly (1-2 sentences) describe the functionality of the component and the reason why the Project is using it.

  - type: textarea
    id: component_details
    attributes:
      label: "Explanation for the need for an exception to the requirement to use the DCO"
    validations:
      required: true

