---
name: DCO Exception Request
description: Submit an exception request
title: "[DCO Exception Request] [Project]"
labels:
  - licensing
assignees: krook,jeefy,joannalee333
body:
  - type: markdown
    attributes:
      value: |
        Under Section 11(b)(ii) of the [CNCF Charter](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy), all inbound code contributions to the CNCF must be accompanied by a Developer Certificate of Origin (DCO). 
        
        To enforce this requirement, all CNCF Projects must enable the [DCO GitHub App](https://github.com/apps/dco) unless an exception is approved by the CNCF Governing Board after review by the Legal Committee.


        # Read before proceeding

        Before submitting this DCO Exception Request, please familiarize yourself with the following:

        - the DCO requirement set forth in [section 11(b)(i) of the CNCF Charter](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy)
        - the [reasons why the Developer Certificate of Origin (DCO) is used and how it can be easily installed as a GitHub app](https://github.com/apps/dco)

        <br />

        ---

        # DCO Exception Request form

        The following information will help facilitate the review by the CNCF Legal Committee and Governing Board, and will help minimize further questions during review.

  - type: markdown
    attributes:
      value: |
        <br />
        
        ## :clipboard: Project details

  - type: input
    id: project_name
    attributes:
      label: "For which CNCF project are you requesting an exception?"
    validations:
      required: true

  - type: dropdown
    id: is_maintainer
    attributes:
      label: "Are you an official maintainer of this project?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br />
        
        ## :newspaper: Exception details

  - type: textarea
    id: component_details
    attributes:
      label: "Please provide the background and reason(s) for your DCO exception request"
    validations:
      required: true

