---
name: Licensing Exception Request
description: Submit an exception request
title: "[License Exception Request] [Project] [License]"
labels:
  - licensing
assignees: krook,jeefy,joannalee333
body:
  - type: markdown
    attributes:
      value: |
        ## Read before proceeding
        Before submitting this license exception request, please familiarize yourself with the following:
          - [CNCF IP Policy, from section 11 of the CNCF Charter, particularly 11(g)](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)
          - [CNCF Allowlist License Policy](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)
          - [HOWTO for submitting a license exception request](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)

        
        If the license for a particular component or dependency is one of the following, please also read the noted guidance before proceeding:
          - **AGPL-3.0 (Affero GPL v3)**: [AGPL guidance](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)
          - **A component that has relicensed to a non-open source, “source available” license**: [Source available guidance](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)
          - **Interactions generally with source available and other proprietary licenses**: [Proprietary / source available guidance](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)

        
        ### When no exception is required
        No exception request is required if the component meets any of the following:
        - is entirely licensed under Apache-2.0 for code; or
        - is entirely licensed under CC-BY-4.0 for documentation; or
        - satisfies the [CNCF Allowlist License Policy](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md); or
        - is subject to a blanket exception that has been granted previously ([see here](https://github.com/cncf/foundation/blob/main/license-exceptions/README.md)) or another previously-granted exception for an equivalent use case.

  - type: input
    id: project_name
    attributes:
      label: "For which CNCF project are you requesting exceptions?"
    validations:
      required: true

  - type: dropdown
    id: is_maintainer
    attributes:
      label: "Are you an official maintainer of this project?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: component_details
    attributes:
      label: "Component Details"
      description: "Please fill in the table below, with one row for each unique component for which a license exception is requested."
      placeholder: "| Component | Upstream URL | License(s) | Purpose |\n|-----------|-------------|------------|---------|"
    validations:
      required: true

  - type: dropdown
    id: mandatory_dependencies
    attributes:
      label: "Are all of the components mandatory dependencies for the project to function as intended?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: mandatory_dependencies_explanation
    attributes:
      label: "If no, please explain"
      description: "Provide details on why some components are not mandatory."
    validations:
      required: false

  - type: checkboxes
    id: inclusion_method
    attributes:
      label: "Please select all of the following that apply to how the components will be included in or with the project’s code and distributions:"
      options:
        - label: "Incorporated code"
        - label: "Vendored component"
        - label: "Build-time dependency"
        - label: "Build and test tooling"
        - label: "Install-time dependency"
        - label: "Required upstream dependencies"
        - label: "Other (please describe below)"

  - type: textarea
    id: inclusion_method_explanation
    attributes:
      label: "If any of the above selections don’t apply to all of the components listed in the table above, please explain"
    validations:
      required: false

  - type: checkboxes
    id: interaction_nature
    attributes:
      label: "Which of the following best describes how the components interact with the project’s own code? (select all that apply)"
      options:
        - label: "Static linking: e.g., compiled together with project code into a single binary"
        - label: "Dynamic linking: e.g., compiled into a separate binary, running together with project code in a single address space at run-time"
        - label: "Separate process: e.g., separate executable running in a different process space, interacting with project code only via mechanisms such as pipes, sockets, etc."
        - label: "Network interaction only: e.g., logically separated over a network and communicating only via mechanisms such as network API call, exchanging JSON data, etc."
        - label: "Other (please describe below)"

  - type: textarea
    id: interaction_explanation
    attributes:
      label: "If any of the above selections don’t apply to all of the components listed in the table above, please explain"
    validations:
      required: false

  - type: dropdown
    id: modifications
    attributes:
      label: "Will any of the components be modified?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: modifications_details
    attributes:
      label: "If yes, please specify which components will be modified, and briefly describe the purpose and nature of the modifications."
    validations:
      required: false

  - type: dropdown
    id: upstream_contribution
    attributes:
      label: "Will the project be seeking to contribute the modifications back to the upstream project?"
      options:
        - "Yes"
        - "No"
    validations:
      required: false
